# Dependencies
highlighter:   rouge
gems:          [jekyll-paginate]

# Permalinks
permalink:    pretty

# Setup
title:        Hack The World
tagline:      'Juan Carlos Jimenez'
description:  'Projects and learnt lessons on Systems Security, Embedded Development, IoT and anything worth writing about'
url:          http://jcjc-dev.com
baseurl:      /

disqusid: jcjc-dev

author:
    name:      'Juan Carlos Jimenez'
    twitter:   https://twitter.com/Palantir555
    linkedin:  https://uk.linkedin.com/in/juan-carlos-jiménez-bba49033
    gh:        https://github.com/Palantir555

paginate:      5

# Custom vars
version:       2.1.0

github:
    repo:      https://github.com/Palantir555
